quotes_data = {
    "Aatrox" :( "Aatrox swings with fury!", "lol_aatrox"),
    "Ahri" :( "Ahri's charm never fails.", "lol_ahri"),
    "Akali" :( "Akali strikes from the shadows.", "lol_akali"),
    "Akshan" :( "Akshan's comeback is real!", "lol_akshan"),
    "Alistar" :( "Alistar's a bull in a fight.", "lol_alistar"),
    "Ambessa" :( "Ambessa's fury knows no bounds!", "lol_ambessa"),
    "Amumu" :( "Amumu just wants a hug.", "lol_amumu"),
    "Anivia" :( "Anivia's frost never melts.", "lol_anivia"),
    "Annie" :( "Annie's bear is ready to play!", "lol_annie"),
    "Aphelios" :( "Aphelios aims for the stars.", "lol_aphelios"),
    "Ashe" :( "Ashe's arrow never misses.", "lol_ashe"),
    "Aurelion Sol" :( "Aurelion Sol controls the stars.", "lol_aurelionsol"),
    "Aurora" :( "Aurora's warmth heals all.", "lol_aurora"),
    "Azir" :( "Azir's empire will rise again.", "lol_azir"),
    "Bard" :( "Bard's journey never ends.", "lol_bard"),
    "Bel'Veth" :( "Bel'Veth's hunger is endless.", "lol_belveth"),
    "Blitzcrank" :( "Blitzcrank grabs everything.", "lol_blitzcrank"),
    "Brand" :( "Brand's fire burns bright.", "lol_brand"),
    "Braum" :( "Braum's heart is as big as his shield.", "lol_braum"),
    "Briar" :( "Briar's fury knows no limits.", "lol_briar"),
    "Caitlyn" :( "Caitlyn's shot is always true.", "lol_caitlyn"),
    "Camille" :( "Camille's precision cuts deep.", "lol_camille"),
    "Cassiopeia" :( "Cassiopeia's gaze is deadly.", "lol_cassiopeia"),
    "Cho'Gath" :( "Cho'Gath eats the strongest.", "lol_chogath"),
    "Corki" :( "Corki's rockets are on target!", "lol_corki"),
    "Darius" :( "Darius brings the pain!", "lol_darius"),
    "Diana" :( "Diana's moonlit strike is swift.", "lol_diana"),
    "Draven" :( "Draven spins to win!", "lol_draven"),
    "Dr. Mundo" :( "Dr. Mundo's pain is his power.", "lol_drmundo"),
    "Ekko" :( "Ekko's time-bending tricks rule.", "lol_ekko"),
    "Elise" :( "Elise's web is everywhere.", "lol_elise"),
    "Evelynn" :( "Evelynn loves to dance in the dark.", "lol_evelynn"),
    "Ezreal" :( "Ezreal's always chasing adventure.", "lol_ezreal"),
    "Fiddlesticks" :( "Fiddlesticks harvests fear.", "lol_fiddlesticks"),
    "Fiora" :( "Fiora's blade is unstoppable.", "lol_fiora"),
    "Fizz" :( "Fizz's tricks are deep in the sea.", "lol_fizz"),
    "Galio" :( "Galio stands tall for justice.", "lol_galio"),
    "Gangplank" :( "Gangplank's cannon is ready.", "lol_gangplank"),
    "Garen" :( "Garen's spinning to win!", "lol_garen"),
    "Gnar" :( "Gnar's rage is wild and free.", "lol_gnar"),
    "Gragas" :( "Gragas' barrel always lands.", "lol_gragas"),
    "Graves" :( "Graves never misses his shot.", "lol_graves"),
    "Gwen" :( "Gwen stitches her way to victory.", "lol_gwen"),
    "Hecarim" :( "Hecarim rides with death's speed.", "lol_hecarim"),
    "Heimerdinger" :( "Heimerdinger's machines rule.", "lol_heimerdinger"),
    "Hwei" :( "Hwei's claws strike fast.", "lol_hwei"),
    "Illaoi" :( "Illaoi's test of strength awaits.", "lol_illaoi"),
    "Irelia" :( "Irelia's blades cut through it all.", "lol_irelia"),
    "Ivern" :( "Ivern's forest is full of life.", "lol_ivern"),
    "Janna" :( "Janna's winds protect all.", "lol_janna"),
    "Jarvan IV" :( "Jarvan's flag leads the charge.", "lol_jarvaniv"),
    "Jax" :( "Jax always has a trick up his sleeve.", "lol_jax"),
    "Jayce" :( "Jayce's hammer crushes all.", "lol_jayce"),
    "Jhin" :( "Jhin's art is deadly perfection.", "lol_jhin"),
    "Jinx" :( "Jinx loves a big bang!", "lol_jinx"),
    "Kaisa" :( "Kaisa's void pulse is deadly.", "lol_kaisa"),
    "Kalista" :( "Kalista's vengeance is swift.", "lol_kalista"),
    "Karma" :( "Karma's spirit guides the way.", "lol_karma"),
    "Karthus" :( "Karthus' song is a dirge.", "lol_karthus"),
    "Kassadin" :( "Kassadin's void powers rule.", "lol_kassadin"),
    "Katarina" :( "Katarina's blades never miss.", "lol_katarina"),
    "Kayle" :( "Kayle's justice is burning bright.", "lol_kayle"),
    "Kayn" :( "Kayn's shadow seeks control.", "lol_kayn"),
    "Kennen" :( "Kennen's lightning strikes fast.", "lol_kennen"),
    "Kha'Zix" :( "Kha'Zix evolves to survive.", "lol_khazix"),
    "Kindred" :( "Kindred's hunt is eternal.", "lol_kindred"),
    "Kled" :( "Kled charges into battle!", "lol_kled"),
    "Kog'Maw" :( "Kog'Maw devours everything.", "lol_kogmaw"),
    "K'Sante" :( "K'Sante fights for his people.", "lol_ksante"),
    "LeBlanc" :( "LeBlanc's tricks never end.", "lol_leblanc"),
    "Lee Sin" :( "Lee Sin's kicks never miss.", "lol_leesin"),
    "Leona" :( "Leona shines with the sun.", "lol_leona"),
    "Lillia" :( "Lillia's dreams protect all.", "lol_lillia"),
    "Lissandra" :( "Lissandra controls the cold.", "lol_lissandra"),
    "Lucian" :( "Lucian's bullets find their mark.", "lol_lucian"),
    "Lulu" :( "Lulu's magic is mischievous.", "lol_lulu"),
    "Lux" :( "Lux's light guides the way.", "lol_lux"),
    "Malphite" :( "Malphite crushes with earth's might.", "lol_malphite"),
    "Malzahar" :( "Malzahar's void never stops.", "lol_malzahar"),
    "Maokai" :( "Maokai roots out the enemies.", "lol_maokai"),
    "Master Yi" :( "Master Yi's strike is swift.", "lol_masteryi"),
    "Milio" :( "Milio's warmth heals all.", "lol_milio"),
    "Miss Fortune" :( "Miss Fortune's shots are true.", "lol_missfortune"),
    "Mordekaiser" :( "Mordekaiser's metal crushes.", "lol_mordekaiser"),
    "Morgana" :( "Morgana's chains bind all.", "lol_morgana"),
    "Naafiri" :( "Naafiri's hunt is relentless.", "lol_naafiri"),
    "Nami" :( "Nami's waves heal all.", "lol_nami"),
    "Nasus" :( "Nasus grows stronger with time.", "lol_nasus"),
    "Nautilus" :( "Nautilus drags you under.", "lol_nautilus"),
    "Neeko" :( "Neeko's trickery knows no bounds.", "lol_neeko"),
    "Nidalee" :( "Nidalee strikes with precision.", "lol_nidalee"),
    "Nilah" :( "Nilah's dance is fierce.", "lol_nilah"),
    "Nocturne" :( "Nocturne's nightmare is real.", "lol_nocturne"),
    "Nunu" :( "Nunu's snowball always wins.", "lol_nunu"),
    "Olaf" :( "Olaf's rage never ends.", "lol_olaf"),
    "Orianna" :( "Orianna's ball controls all.", "lol_orianna"),
    "Ornn" :( "Ornn forges his destiny.", "lol_ornn"),
    "Pantheon" :( "Pantheon's spear never misses.", "lol_pantheon"),
    "Poppy" :( "Poppy's hammer strikes hard.", "lol_poppy"),
    "Pyke" :( "Pyke's hook drags you down.", "lol_pyke"),
    "Qiyana" :( "Qiyana's power rules the elements.", "lol_qiyana"),
    "Quinn" :( "Quinn's bird sees all.", "lol_quinn"),
    "Rakan" :( "Rakan dances to his own tune.", "lol_rakan"),
    "Rammus" :( "Rammus rolls into action!", "lol_rammus"),
    "Rek'Sai" :( "Rek'Sai tunnels for you.", "lol_reksai"),
    "Rell" :( "Rell's iron will is unbreakable.", "lol_rell"),
    "Renata" :( "Renata's business is ruthless.", "lol_renata"),
    "Renekton" :( "Renekton's bite is deadly.", "lol_renekton"),
    "Rengar" :( "Rengar hunts for the thrill.", "lol_rengar"),
    "Riven" :( "Riven's blade never breaks.", "lol_riven"),
    "Rumble" :( "Rumble's mech always wins.", "lol_rumble"),
    "Ryze" :( "Ryze's magic warps reality.", "lol_ryze"),
    "Samira" :( "Samira's style kills.", "lol_samira"),
    "Sejuani" :( "Sejuani's winter reigns.", "lol_sejuani"),
    "Senna" :( "Senna's shots bring light.", "lol_senna"),
    "Seraphine" :( "Seraphine sings for you.", "lol_seraphine"),
    "Sett" :( "Sett fights with power.", "lol_sett"),
    "Shaco" :( "Shaco's tricks will get you.", "lol_shaco"),
    "Shen" :( "Shen's spirit guides the way.", "lol_shen"),
    "Shyvana" :( "Shyvana burns with fury.", "lol_shyvana"),
    "Singed" :( "Singed's poison never fades.", "lol_singed"),
    "Sion" :( "Sion's rage is unstoppable.", "lol_sion"),
    "Sivir" :( "Sivir's boomerang always returns.", "lol_sivir"),
    "Skarner" :( "Skarner's sting is fierce.", "lol_skarner"),
    "Smolder" :( "Smolder's flames scorch all.", "lol_smolder"),
    "Sona" :( "Sona's music heals you.", "lol_sona"),
    "Soraka" :( "Soraka's healing is endless.", "lol_soraka"),
    "Swain" :( "Swain's ravens never miss.", "lol_swain"),
    "Sylas" :( "Sylas steals your power.", "lol_sylas"),
    "Syndra" :( "Syndra controls the stars.", "lol_syndra"),
    "TahmKench" :( "Tahm Kench swallows you whole.", "lol_tahmkench"),
    "Taliyah" :( "Taliyah's stones always land.", "lol_taliyah"),
    "Talon" :( "Talon strikes from the shadows.", "lol_talon"),
    "Taric" :( "Taric's gem shines bright.", "lol_taric"),
    "Teemo" :( "Teemo's poison never fades.", "lol_teemo"),
    "Thresh" :( "Thresh drags you to darkness.", "lol_thresh"),
    "Tristana" :( "Tristana's rocket never stops.", "lol_tristana"),
    "Trundle" :( "Trundle rules the ice.", "lol_trundle"),
    "Tryndamere" :( "Tryndamere's fury never dies.", "lol_tryndamere"),
    "Twisted Fate" :( "Twisted Fate's luck never runs out.", "lol_twistedfate"),
    "Twitch" :( "Twitch is always sneaky.", "lol_twitch"),
    "Udyr" :( "Udyr channels the wild.", "lol_udyr"),
    "Urgot" :( "Urgot's terror never ends.", "lol_urgot"),
    "Varus" :( "Varus's arrow strikes true.", "lol_varus"),
    "Vayne" :( "Vayne hunts the darkness.", "lol_vayne"),
    "Veigar" :( "Veigar's power is limitless.", "lol_veigar"),
    "Vel'Koz" :( "Vel'Koz sees everything.", "lol_velkoz"),
    "Vex" :( "Vex's gloom spreads fast.", "lol_vex"),
    "Vi" :( "Vi's punch knocks hard.", "lol_vi"),
    "Viego" :( "Viego's love is deadly.", "lol_viego"),
    "Viktor" :( "Viktor's power reshapes reality.", "lol_viktor"),
    "Vladimir" :( "Vladimir's blood is his power.", "lol_vladimir"),
    "Volibear" :( "Volibear's thunder cracks loud.", "lol_volibear"),
    "Wukong" :( "Wokong's staff strikes hard.", "lol_monkeyking"),
    "Warwick" :( "Warwick hunts with hunger.", "lol_warwick"),
    "Xayah" :( "Xayah's feathers never miss.", "lol_xayah"),
    "Xerath" :( "Xerath controls the arcane.", "lol_xerath"),
    "Xin Zhao" :( "Xin Zhao's spear strikes fast.", "lol_xinzhao"),
    "Yasuo" :( "Yasuo's wind is unstoppable.", "lol_yasuo"),
    "Yone" :( "Yone's sword strikes twice.", "lol_yone"),
    "Yorick" :( "Yorick controls the graves.", "lol_yorick"),
    "Yuumi" :( "Yuumi's magic heals all.", "lol_yuumi"),
    "Zac" :( "Zac bounces back every time.", "lol_zac"),
    "Zed" :( "Zed's shadows strike hard.", "lol_zed"),
    "Zeri" :( "Zeri's speed never slows.", "lol_zeri"),
    "Ziggs" :( "Ziggs' bombs always explode.", "lol_ziggs"),
    "Zilean" :( "Zilean's time rewinds fast.", "lol_zilean"),
    "Zoe" :( "Zoe's mischief knows no bounds.", "lol_zoe"),
    "Zyra" :( "Zyra's plants never sleep.", "lol_zyra")
}